//Autogenerated
using System;
using System.Collections;
using System.Collections.Generic;

[Serializable]
public class ItemStaticData
{
	public int Id;
	public string Name;
	public string Description;
}