//Autogenerated
using System;
using System.Collections;
using System.Collections.Generic;

[Serializable]
public class PersonStaticData
{
	public int Id;
	public string Name;
	public int Age;
	public StaticRef Items;
	public StaticRef Additional;
}